### ISSUE TITLE
esgf authentication

### ISSUE THREAD

**Issue by mattben** [CDAT/cdatweb#67]
Using the https://github.com/ACME-OUI/esgf-pyclient finish adding esgf
authentication to cdatweb

Production Server: http://acme-cdatweb.ornl.gov
Devel Server: http://cdatweb-devel.llnl.gov

**Comment by aashish24** [comment]
:+1:

**Comment by jbeezley** [comment]
Implemented by: #69 
Testing and deployment blocked by: https://github.com/UV-CDAT/uvcdat/issues/1337

**Comment by mattben** [comment]
@jbeezley whats the current status?

**Comment by jbeezley** [comment]
See my comment here: https://github.com/UV-CDAT/uvcdat/issues/1337#issuecomment-175703062

**Comment by aashish24** [comment]
@mattben @jbeezley lets work on the local filesystem first. I think the ESGF issue is causing a lot of work for us.

**Comment by mattben** [comment]
Dead Project
