### ISSUE TITLE
Nice Names

### ISSUE THREAD

**Issue by mattben** [CDAT/cdatweb#90]
vis server should return nice names for variables and templates as well as abbreviations

**Comment by jbeezley** [comment]
We can provide better names for the templates.  If someone who understands what the templates are can give me a mapping of uv-cdat -> nice name,  I can do the rest in about 5 minutes.

I don't know how I can provide nice names for variables in netcdf files though.  I'll need more information about what is wanted.

**Comment by mattben** [comment]
@doutriaux1 can you create a quick text file with a nice name for the templates please?
@chaosphere2112 how do we get the nice names out?

**Comment by chaosphere2112** [comment]
@jbeezley Most of the "nice" variable names are stored in the `title` or `long_name` attributes, though both of those are optional and raise `AttributeError`s if you try and access them when they aren't present. I usually use a 3-way try/except:

```python
try:
    name = variable.long_name
except AttributeError:
    try:
        name = variable.title
    except:
        name = variable.id
```

As for the "nice names" of templates, I was really just planning on using the ugly names in the GUI. Users can create their own templates and give them arbitrary names. Much more useful than naming them would be providing a preview of what they look like (which is a thing I'll be doing).

**Comment by chaosphere2112** [comment]
@jbeezley I'll do up a VCS script that you can use to generate template previews, we can both use it

**Comment by doutriaux1** [comment]
@mattben @jbeezley yep the templates `nice name` is really up to the users, most of the `uggly` names stem from historical 8 or so characters limit issues. They have been used for many years now and most of the vcs community is used to them and they make perfect sense to them. e.g `dud` means no text or many ticks etc... `1of3` etc makes sense too.

**Comment by jbeezley** [comment]
@chaosphere2112 sounds great.  I can do that for the variables names, and I'll wait for your vcs magic to generate previews.

**Comment by mattben** [comment]
Dead Project
